model:
  name: "SR3"
  constrained: False 
  threshold: 0.001
  max_iter: 30
  verbose: False
  library_functions: "sin"
  bagging: False 
  n_models: 100
  library_ensemble: False 

dynamics_name: "kuramoto"

simulations:
  dt_train: 0.001
  t_max_train: 1
  N_simulations_train: 60
  N_simulations_train_max: 20000
  dt_test: 0.001
  t_max_test: 10
  N_simulations_test: 1
  N_simulations_test_max: 20000
  number_train_different_q0: 1
  filename_initial_conditions_training:  
    - "train/32-q0_training.csv" 
  filename_initial_conditions_testing:  
    - "test/32-q0_testing.csv" 
  filename_parameters:  
    - "param/32-par_K_10_100.csv"
  transient: True
  synchronized: True
  

networks:
  topology: 'BA'
  directory: './../../networks'
  N_nodes: 
    - 32
  N_config: 1
  start_scan: 1
  end_scan: 100
  d_scan: 1

processing:
  integrate_sindy_equations: True
  skip_dynamics_with_warning: True
  debug: False
  write_output: True
  filename_output: './output/32-BA-1-100-K_10_100-kuramoto_less.csv'
  save_all: False 
  replicable: True
  timeout_integration: 30
  timeout_max_value: 63
